
import java.util.Vector;
import javax.swing.ListModel;
import javax.swing.ListSelectionModel;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author Ishfaq Haider 1418-FBAS/BSSE/F11A
 */
public class MainChatPanel extends javax.swing.JPanel {

    /**
     * Creates new form MainChatPanel
     */
    public MainChatPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPaneFriends = new javax.swing.JScrollPane();
        jList_Vector=new Vector();
        jListFriend = new javax.swing.JList(jList_Vector);
        jScrollPaneHistory = new javax.swing.JScrollPane();
        jTextAreaHistory = new javax.swing.JTextArea();
        jScrollPaneMessege = new javax.swing.JScrollPane();
        jTextAreaMessege = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jButtonSend = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabelYou = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(400, 350));
        setVerifyInputWhenFocusTarget(false);

        /*
        jListFriend.setModel(null);
        */
        jListFriend.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        jListFriend.setSelectionBackground(new java.awt.Color(204, 255, 255));
        jScrollPaneFriends.setViewportView(jListFriend);

        jTextAreaHistory.setColumns(20);
        jTextAreaHistory.setRows(5);
        jScrollPaneHistory.setViewportView(jTextAreaHistory);

        jTextAreaMessege.setColumns(20);
        jTextAreaMessege.setRows(5);
        jScrollPaneMessege.setViewportView(jTextAreaMessege);
        jTextAreaMessege.getAccessibleContext().setAccessibleName("");

        jLabel1.setText("        Select a friend");

        jButtonSend.setText("Send");
        jButtonSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSendActionPerformed(evt);
            }
        });

        jLabel2.setText("You are login as:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPaneMessege, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                        .addComponent(jScrollPaneHistory))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelYou, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                    .addComponent(jScrollPaneFriends, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jButtonSend, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelYou, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPaneHistory)
                    .addComponent(jScrollPaneFriends, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPaneMessege, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jButtonSend, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)))
        );

        getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSendActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSendActionPerformed
public Vector jList_Vector;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonSend;
    public javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabelYou;
    public javax.swing.JList jListFriend;
    public javax.swing.JScrollPane jScrollPaneFriends;
    public javax.swing.JScrollPane jScrollPaneHistory;
    public javax.swing.JScrollPane jScrollPaneMessege;
    public javax.swing.JTextArea jTextAreaHistory;
    public javax.swing.JTextArea jTextAreaMessege;
    // End of variables declaration//GEN-END:variables
}
